version: "3.7"
services:
  credit-server:
    container_name: exchange-server
    build: .
    restart: always
    depends_on:
      - mongo_db
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8103:8103"
  mongo_db:
    image: "mongo:5.0.1"
    restart: always
    ports:
      - "27030:27017"
networks:
  default:
    name: custom-network